//
// Created by spaceman on 2021. 01. 09..
//

#ifndef SRC_CONSTANTS_CUH
#define SRC_CONSTANTS_CUH

#define DEFAULT_TRAINING_FILENAME "optdigits.tra"
#define DEFAULT_TEST_FILENAME "optdigits.tes"

#ifndef DEFAULT_SOM_FILENAME
#define DEFAULT_SOM_FILENAME "som.txt"
#endif

#ifndef DEFAULT_MAP_WIDTH
#define DEFAULT_MAP_WIDTH 10
#endif

#ifndef DEFAULT_MAP_HEIGHT
#define DEFAULT_MAP_HEIGHT 10
#endif

#ifndef ANIMATION_DEFAULT_FRAMECOUNT
#define ANIMATION_DEFAULT_FRAMECOUNT 100
#endif

#ifndef CLASSIFICATION_DEFAULT_CLASS_COUNT
#define CLASSIFICATION_DEFAULT_CLASS_COUNT 10
#endif

#ifndef DEAFULT_COUNT_CROSS_VALIDATION_K
#define DEAFULT_COUNT_CROSS_VALIDATION_K 10
#endif

#define OPTION_FLAG_PATH_TEST_INPUT "test"
#define OPTION_FLAG_PATH_TRAIN_INPUT "input"
#define OPTION_FLAG_PATH_SOM_OUTPUT "outputPath"
#define OPTION_FLAG_PATH_OUTPUT_ANIMATION "animationPath"

#define OPTION_FLAG_DIM_WIDTH_IMAGE "imagew"
#define OPTION_FLAG_DIM_HEIGHT_IMAGE "imageh"
#define OPTION_FLAG_DIM_WIDTH_MAP "mapw"
#define OPTION_FLAG_DIM_HEIGHT_MAP "maph"

#define OPTION_FLAG_COUNT_TRAIN_SOM_MAX_ITERATION "gen"
#define OPTION_FLAG_COUNT_ANIMATION_FRAMES "framecount"

#define OPTION_FLAG_ON_ANIMATION "animation"



#endif //SRC_CONSTANTS_CUH
