SOM: digits.cu SOM.cu digitSet.cu digit.cu cuda.cu
	nvcc digits.cu --std=c++14 -o SOM -g
	mv SOM ..
#	g++ digits.cpp ocr.cpp  ocr.cu   --std=c++14  -lpthread -larmadillo -O3 
#g++ digits.cpp ocr.cpp  ocr.h -Dknn -Dcentroid -Dlregression    --std=c++11  -lpthread -larmadillo -O3 
